import { FilterState, SortOption } from './types';

export const CATEGORIES: Record<string, string> = {
  'meeting-notes': 'Meeting Notes',
  'voice-dictation': 'Dictation',
  'link-in-bio': 'Link in Bio',
  'social-media': 'Social Media',
  'seo-marketing': 'SEO & Marketing',
  devtools: 'Dev Tools',
  'ai-writing': 'AI Writing',
  'ai-assistant': 'AI Assistants',
  automation: 'Automation',
  analytics: 'Analytics',
  design: 'Design',
  'website-builders': 'Website Builders',
  'notes-knowledge': 'Notes & Knowledge',
  hosting: 'Hosting',
  commerce: 'Commerce',
  scheduling: 'Scheduling',
  'forms-surveys': 'Forms & Surveys',
  'screen-recording': 'Screen Recording',
  'photo-editing': 'Photo Editing',
  'sales-outreach': 'Sales Outreach',
  newsletters: 'Newsletters',
  'customer-support': 'Customer Support',
  'project-management': 'Project Management',
  'personal-finance': 'Personal Finance',
  security: 'Security',
  'docs-databases': 'Documents & DBs',
  'video-conferencing': 'Video Calls',
  podcasting: 'Podcasting',
};

export const CATEGORY_EMOJI: Record<string, string> = {
  all: 'Ã¢Å¡Â¡',
  'meeting-notes': 'Ã°Å¸Å½â„¢Ã¯Â¸Â',
  'voice-dictation': 'Ã°Å¸â€”Â£Ã¯Â¸Â',
  'link-in-bio': 'Ã°Å¸â€â€”',
  'social-media': 'Ã°Å¸ÂÂ¦',
  'seo-marketing': 'Ã°Å¸â€œË†',
  devtools: 'Ã°Å¸â€ºÂ Ã¯Â¸Â',
  'ai-writing': 'Ã¢Å“ÂÃ¯Â¸Â',
  'ai-assistant': 'Ã°Å¸Â¤â€“',
  automation: 'Ã¢Å¡â„¢Ã¯Â¸Â',
  analytics: 'Ã°Å¸â€œÅ ',
  design: 'Ã°Å¸Å½Â¨',
  'website-builders': 'Ã°Å¸Â§Â±',
  'notes-knowledge': 'Ã°Å¸Â§Â ',
  hosting: 'Ã¢ËœÂÃ¯Â¸Â',
  commerce: 'Ã°Å¸â€ºâ€™',
  scheduling: 'Ã°Å¸â€œâ€¦',
  'forms-surveys': 'Ã°Å¸â€œâ€¹',
  'screen-recording': 'Ã°Å¸Å½Â¬',
  'photo-editing': 'Ã°Å¸â€œÂ¸',
  'sales-outreach': 'Ã°Å¸â€œÂ§',
  newsletters: 'Ã°Å¸â€œÂ°',
  'customer-support': 'Ã°Å¸â€™Â¬',
  'project-management': 'Ã°Å¸â€œÂ',
  'personal-finance': 'Ã°Å¸â€™Â°',
  security: 'Ã°Å¸â€â€™',
  'docs-databases': 'Ã°Å¸â€”â€žÃ¯Â¸Â',
  'video-conferencing': 'Ã°Å¸â€œÂ¹',
  podcasting: 'Ã°Å¸Å½Â§',
};

export const MOAT_TAGS: Record<string, string> = {
  'network-effects': 'Network Effects',
  'marketplace-liquidity': 'Marketplace Liquidity',
  'proprietary-data': 'Proprietary Data',
  'proprietary-models': 'Proprietary Models',
  'switching-costs': 'Switching Costs',
  integrations: 'Integrations',
  'compliance-regulatory': 'Compliance',
  'brand-trust': 'Brand Trust',
  'scale-infra': 'Scale / Infra',
  hardware: 'Hardware',
  collaboration: 'Collaboration',
  'content-rights': 'Content Rights',
  'execution-polish': 'Execution Polish',
};

export const INITIAL_FILTER: FilterState = {
  verdict: 'all',
  category: 'all',
  teamSize: 1,
  sort: 'votes',
  search: '',
};

export const AD_INTERVAL = 10;
