import { FilterState, SortOption } from './types';

export const CATEGORIES: Record<string, string> = {
  'meeting-notes': 'Meeting Notes',
  'voice-dictation': 'Dictation',
  dictation: 'Dictation',
  'link-in-bio': 'Link in Bio',
  'social-media': 'Social Media',
  'seo-marketing': 'SEO & Marketing',
  'dev-tools': 'Dev Tools',
  'ai-writing': 'AI Writing',
  'ai-assistant': 'AI Assistants',
  'ai-assistants': 'AI Assistants',
  automation: 'Automation',
  analytics: 'Analytics',
  design: 'Design',
  'website-builders': 'Website Builders',
  'notes-knowledge': 'Notes & Knowledge',
  hosting: 'Hosting',
  commerce: 'Commerce',
  scheduling: 'Scheduling',
  'forms-surveys': 'Forms & Surveys',
  'screen-recording': 'Screen Recording',
  'photo-editing': 'Photo Editing',
  'sales-outreach': 'Sales Outreach',
  newsletters: 'Newsletters',
  'customer-support': 'Customer Support',
  'project-management': 'Project Management',
  'personal-finance': 'Personal Finance',
  security: 'Security',
  'docs-databases': 'Documents & DBs',
  'video-conferencing': 'Video Calls',
  podcasting: 'Podcasting',
  'creator-commerce': 'Creator Commerce',
  email: 'Email',
  'productivity-utilities': 'Productivity',
  'audio-video': 'Audio & Video',
  'finance-accounting': 'Finance & Accounting',
  forms: 'Forms',
  tasks: 'Tasks',
  'ai-images': 'AI Images',
  'read-it-later': 'Read It Later',
  'no-code-apps': 'No-Code Apps',
  diagrams: 'Diagrams',
  community: 'Community',
  'generative-media': 'Generative Media',
  'user-research': 'User Research',
  'ai-video': 'AI Video',
  'documents-pdfs': 'Documents & PDFs',
  'music-audio': 'Music & Audio',
  crm: 'CRM',
  'cloud-storage': 'Cloud Storage',
  databases: 'Databases',
  'video-calls': 'Video Calls',
  'voice-ai': 'Voice AI',
  'time-tracking': 'Time Tracking',
  travel: 'Travel',
  home: 'Home',
  education: 'Education',
  hr: 'HR',
  wellness: 'Wellness',
  career: 'Career',
  legal: 'Legal',
  localization: 'Localization',
  monitoring: 'Monitoring',
  'writing-tools': 'Writing Tools',
  reading: 'Reading',
  'rss-research': 'RSS & Research',
  presentations: 'Presentations',
  'tasks-calendar': 'Tasks & Calendar',
  whiteboards: 'Whiteboards',
  testimonials: 'Testimonials',
  sales: 'Sales',
  operations: 'Operations',
  screenshots: 'Screenshots',
  'cron-monitoring': 'Cron Monitoring',
  waitlists: 'Waitlists',
  publishing: 'Publishing',
  'ai-search': 'AI Search',
  'qr-codes': 'QR Codes',
  bookmarks: 'Bookmarks',
  'ai-audio': 'AI Audio',
  personal: 'Personal',
  uptime: 'Uptime',
};

export const CATEGORY_EMOJI: Record<string, string> = {
  all: '⚡',
  'meeting-notes': '🎙️',
  'voice-dictation': '🗣️',
  dictation: '🗣️',
  'link-in-bio': '🔗',
  'social-media': '🐦',
  'seo-marketing': '📈',
  'dev-tools': '🛠️',
  'ai-writing': '✍️',
  'ai-assistant': '🤖',
  'ai-assistants': '🤖',
  automation: '⚙️',
  analytics: '📊',
  design: '🎨',
  'website-builders': '🧱',
  'notes-knowledge': '🧠',
  hosting: '☁️',
  commerce: '🛒',
  scheduling: '📅',
  'forms-surveys': '📋',
  'screen-recording': '🎬',
  'photo-editing': '📸',
  'sales-outreach': '📧',
  newsletters: '📰',
  'customer-support': '💬',
  'project-management': '📐',
  'personal-finance': '💰',
  security: '🔒',
  'docs-databases': '🗄️',
  'video-conferencing': '📹',
  podcasting: '🎧',
  'creator-commerce': '🛍️',
  email: '📬',
  'productivity-utilities': '🧰',
  'audio-video': '🎥',
  'finance-accounting': '🧾',
  forms: '📋',
  tasks: '✅',
  'ai-images': '🖼️',
  'read-it-later': '🔖',
  'no-code-apps': '🧩',
  diagrams: '🗺️',
  community: '👥',
  'generative-media': '✨',
  'user-research': '🔍',
  'ai-video': '🎞️',
  'documents-pdfs': '📄',
  'music-audio': '🎵',
  crm: '🤝',
  'cloud-storage': '💾',
  databases: '🛢️',
  'video-calls': '📹',
  'voice-ai': '🎤',
  'time-tracking': '⏱️',
  travel: '✈️',
  home: '🏠',
  education: '🎓',
  hr: '👔',
  wellness: '🧘',
  career: '💼',
  legal: '⚖️',
  localization: '🌍',
  monitoring: '🖥️',
  'writing-tools': '🖊️',
  reading: '📖',
  'rss-research': '📡',
  presentations: '📽️',
  'tasks-calendar': '🗓️',
  whiteboards: '🧮',
  testimonials: '⭐',
  sales: '💵',
  operations: '🔄',
  screenshots: '📷',
  'cron-monitoring': '⏰',
  waitlists: '🚀',
  publishing: '📚',
  'ai-search': '🔎',
  'qr-codes': '📱',
  bookmarks: '🏷️',
  'ai-audio': '🔊',
  personal: '🙋',
  uptime: '📶',
};

const CATEGORY_VARIANTS: Record<string, string> = {
  devtools: 'dev-tools',
  'dev tools': 'dev-tools',
  'social media': 'social-media',
  'notes & knowledge': 'notes-knowledge',
  'ai writing': 'ai-writing',
  'seo & marketing': 'seo-marketing',
  'website builders': 'website-builders',
  'ai assistants': 'ai-assistants',
  'meeting notes': 'meeting-notes',
  'screen recording': 'screen-recording',
  'project management': 'project-management',
  'forms & surveys': 'forms-surveys',
  'video-conferencing': 'video-calls',
  'voice-dictation': 'dictation',
};

export function normalizeCategory(category: string): string {
  return CATEGORY_VARIANTS[category] || category;
}

export function categoryLabel(category: string): string {
  return CATEGORIES[normalizeCategory(category)] || normalizeCategory(category);
}

export function categoryEmoji(category: string): string {
  return CATEGORY_EMOJI[normalizeCategory(category)] || '';
}

export const MOAT_TAGS: Record<string, string> = {
  'network-effects': 'Network Effects',
  'marketplace-liquidity': 'Marketplace Liquidity',
  'proprietary-data': 'Proprietary Data',
  'proprietary-models': 'Proprietary Models',
  'switching-costs': 'Switching Costs',
  integrations: 'Integrations',
  'compliance-regulatory': 'Compliance',
  'brand-trust': 'Brand Trust',
  'scale-infra': 'Scale / Infra',
  hardware: 'Hardware',
  collaboration: 'Collaboration',
  'content-rights': 'Content Rights',
  'execution-polish': 'Execution Polish',
};

export const INITIAL_FILTER: FilterState = {
  verdict: 'all',
  category: 'all',
  teamSize: 1,
  sort: 'votes',
  search: '',
  newListed: false,
};

export const AD_INTERVAL = 10;
