import type { AppData } from './types';
import type { SponsorPlacement } from './sponsors';

const SITE = 'https://letsvibecodeit.com';

export function renderWeeklyDigest(apps: AppData[], sponsors: SponsorPlacement[]): string {
  const appRows = apps.length ? apps.map(app => `<tr><td style="padding:12px 0;border-bottom:1px solid #263126"><img src="${favicon(app.domain)}" width="36" height="36" alt="" style="border-radius:9px;vertical-align:middle;margin-right:12px"><a href="${SITE}/${app.slug}" style="color:#58e88d;font-size:16px;font-weight:bold;text-decoration:none">${escapeHtml(app.name)}</a><div style="color:#aab7aa;font-size:13px;margin:5px 0 0 50px">${escapeHtml(app.tagline)}</div></td></tr>`).join('') : '<tr><td style="padding:18px 0;color:#aab7aa">No new apps were added this week. The list is still getting sharper.</td></tr>';
  const sponsorRows = sponsors.length ? sponsors.map(sponsor => `<tr><td style="padding:12px 0;border-bottom:1px solid #263126"><img src="${escapeHtml(sponsor.iconUrl)}" width="36" height="36" alt="" style="border-radius:9px;vertical-align:middle;margin-right:12px"><a href="${escapeHtml(absoluteUrl(sponsor.website))}" style="color:#f5c96a;font-size:16px;font-weight:bold;text-decoration:none">${escapeHtml(sponsor.name)}</a><div style="color:#aab7aa;font-size:13px;margin:5px 0 0 50px">${escapeHtml(sponsor.description)}</div></td></tr>`).join('') : '';
  return `<!doctype html><html><body style="margin:0;background:#0b0d0b;color:#f0f5ef;font-family:Arial,sans-serif"><div style="max-width:620px;margin:0 auto;padding:26px 20px"><header style="border-bottom:1px solid #263126;padding-bottom:20px"><img src="${SITE}/icon-256.png" width="42" height="42" alt="LetsVibeCodeit" style="vertical-align:middle;margin-right:10px;border-radius:11px"><span style="font-size:22px;font-weight:bold;vertical-align:middle">Lets<span style="color:#58e88d">VibeCode</span>it</span><p style="color:#aab7aa;font-size:13px;margin:16px 0 0">The weekly list of subscriptions worth replacing, keeping, or questioning.</p></header><main><h1 style="font-size:28px;margin:30px 0 8px">New this week</h1><p style="color:#aab7aa;font-size:14px;margin:0 0 14px">Fresh apps added to the catalog, with honest verdicts and the trade-offs behind them.</p><table role="presentation" width="100%" cellspacing="0">${appRows}</table>${sponsorRows ? `<h2 style="font-size:20px;margin:34px 0 8px;color:#f5c96a">Weekly digest sponsors</h2><p style="color:#aab7aa;font-size:14px">Support the builders who keep this list moving.</p><table role="presentation" width="100%" cellspacing="0">${sponsorRows}</table>` : ''}</main><footer style="border-top:1px solid #263126;margin-top:34px;padding-top:18px;color:#728072;font-size:12px"><a href="${SITE}" style="color:#58e88d">Open LetsVibeCodeit</a><br><br><a href="{{{RESEND_UNSUBSCRIBE_URL}}}" style="color:#728072">Unsubscribe from the weekly digest</a></footer></div></body></html>`;
}

function favicon(domain: string): string { return `https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=64`; }
function absoluteUrl(value: string): string { return value.startsWith('/') ? `${SITE}${value}` : value; }
function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] || char)); }
